### ISSUE TITLE
Problem Definition

### ISSUE THREAD

**Issue by behroozfarkiani** [1995parham/RoadToMSc#21]
Why your problem has not been completely defined yet? where is the link between VNFM and VNFs? Where is the analysis of the problem?

**Comment by 1995parham** [comment]
Hello Behrooz 😄 
What do you mean by problem definition? In my presentation section, I did my best to complete my formulation and problem definition. did you see that?

**Comment by behroozfarkiani** [comment]
I meant the implementation, of course. The presentation is not important.

**Comment by 1995parham** [comment]
In the implementation, I want to maximize the revenue from placing the chain by considering the VNFM requirement.

**Comment by behroozfarkiani** [comment]
That is not my answer. I asked
> Where is the link between VNFM and VNFs in the implementation
and
> Where is the analysis of the problem? Do you know how it behaves in large instances?
It has been around 6 months without any progress.
